/* tslint:disable */
/* eslint-disable */
/**
 * Mvd
 * The Mvd API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDeviceDto
 */
export interface CreateDeviceDto {
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    randomSymbols: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    scheduleFrequencyPhoto: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    scheduleDurationPhoto: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    scheduleFramesQuantity: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateDeviceDto
     */
    movementCells: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    movementDiffLevel: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    movementChangeFrameTime: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    movementFrequencyAnalyzing: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleDurationBeforeMoveSensor: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleFramesQuantityBeforeMove: number;
    /**
     * 
     * @type {string}
     * @memberof CreateDeviceDto
     */
    circleDurationDuringMoveSensorUnit: CreateDeviceDtoCircleDurationDuringMoveSensorUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleDurationDuringMoveSensor: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleFramesQuantityDuringMove: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleDurationAfterMoveSensor: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeviceDto
     */
    circleFramesQuantityAfterMove: number;
}

export function CreateDeviceDtoFromJSON(json: any): CreateDeviceDto {
    return CreateDeviceDtoFromJSONTyped(json, false);
}

export function CreateDeviceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeviceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'name': json['name'],
        'randomSymbols': json['randomSymbols'],
        'scheduleFrequencyPhoto': json['scheduleFrequencyPhoto'],
        'scheduleDurationPhoto': json['scheduleDurationPhoto'],
        'scheduleFramesQuantity': json['scheduleFramesQuantity'],
        'movementCells': json['movementCells'],
        'movementDiffLevel': json['movementDiffLevel'],
        'movementChangeFrameTime': json['movementChangeFrameTime'],
        'movementFrequencyAnalyzing': json['movementFrequencyAnalyzing'],
        'circleDurationBeforeMoveSensor': json['circleDurationBeforeMoveSensor'],
        'circleFramesQuantityBeforeMove': json['circleFramesQuantityBeforeMove'],
        'circleDurationDuringMoveSensorUnit': json['circleDurationDuringMoveSensorUnit'],
        'circleDurationDuringMoveSensor': json['circleDurationDuringMoveSensor'],
        'circleFramesQuantityDuringMove': json['circleFramesQuantityDuringMove'],
        'circleDurationAfterMoveSensor': json['circleDurationAfterMoveSensor'],
        'circleFramesQuantityAfterMove': json['circleFramesQuantityAfterMove'],
    };
}

export function CreateDeviceDtoToJSON(value?: CreateDeviceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'name': value.name,
        'randomSymbols': value.randomSymbols,
        'scheduleFrequencyPhoto': value.scheduleFrequencyPhoto,
        'scheduleDurationPhoto': value.scheduleDurationPhoto,
        'scheduleFramesQuantity': value.scheduleFramesQuantity,
        'movementCells': value.movementCells,
        'movementDiffLevel': value.movementDiffLevel,
        'movementChangeFrameTime': value.movementChangeFrameTime,
        'movementFrequencyAnalyzing': value.movementFrequencyAnalyzing,
        'circleDurationBeforeMoveSensor': value.circleDurationBeforeMoveSensor,
        'circleFramesQuantityBeforeMove': value.circleFramesQuantityBeforeMove,
        'circleDurationDuringMoveSensorUnit': value.circleDurationDuringMoveSensorUnit,
        'circleDurationDuringMoveSensor': value.circleDurationDuringMoveSensor,
        'circleFramesQuantityDuringMove': value.circleFramesQuantityDuringMove,
        'circleDurationAfterMoveSensor': value.circleDurationAfterMoveSensor,
        'circleFramesQuantityAfterMove': value.circleFramesQuantityAfterMove,
    };
}

/**
* @export
* @enum {string}
*/
export enum CreateDeviceDtoCircleDurationDuringMoveSensorUnitEnum {
    Seconds = 'Seconds',
    Minutes = 'Minutes'
}


