/* tslint:disable */
/* eslint-disable */
/**
 * Mvd
 * The Mvd API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePermissionDto
 */
export interface CreatePermissionDto {
    /**
     * 
     * @type {boolean}
     * @memberof CreatePermissionDto
     */
    addDevice: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePermissionDto
     */
    removeDevice: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePermissionDto
     */
    editDevice: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePermissionDto
     */
    download: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePermissionDto
     */
    removePhoto: boolean;
}

export function CreatePermissionDtoFromJSON(json: any): CreatePermissionDto {
    return CreatePermissionDtoFromJSONTyped(json, false);
}

export function CreatePermissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePermissionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addDevice': json['addDevice'],
        'removeDevice': json['removeDevice'],
        'editDevice': json['editDevice'],
        'download': json['download'],
        'removePhoto': json['removePhoto'],
    };
}

export function CreatePermissionDtoToJSON(value?: CreatePermissionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addDevice': value.addDevice,
        'removeDevice': value.removeDevice,
        'editDevice': value.editDevice,
        'download': value.download,
        'removePhoto': value.removePhoto,
    };
}


