/* tslint:disable */
/* eslint-disable */
/**
 * Mvd
 * The Mvd API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemovePhotosDto
 */
export interface RemovePhotosDto {
    /**
     * 
     * @type {Array<number>}
     * @memberof RemovePhotosDto
     */
    ids: Array<number>;
}

export function RemovePhotosDtoFromJSON(json: any): RemovePhotosDto {
    return RemovePhotosDtoFromJSONTyped(json, false);
}

export function RemovePhotosDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePhotosDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function RemovePhotosDtoToJSON(value?: RemovePhotosDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
    };
}


